USE futBrain;
SHOW TABLES;

CREATE TABLE usuario(
    idUsuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(45),
    email VARCHAR(45),
    senha VARCHAR(45)  
);

CREATE TABLE quizzes(
    idQuiz INT PRIMARY KEY AUTO_INCREMENT,
    liga VARCHAR(45) UNIQUE
);

CREATE TABLE resultado(
    fkUsuario INT,
    fkQuiz INT,
    pontos INT,
    dtQuiz DATETIME,
    PRIMARY KEY (fkUsuario, fkQuiz),
    Foreign Key (fkUsuario) REFERENCES Usuario(idUsuario),
    Foreign Key (fkQuiz) REFERENCES Quizzes(idQuiz)
);

CREATE TABLE perguntas(
    idPergunta INT AUTO_INCREMENT,
    fkQuiz INT,
    descricao VARCHAR(100),
    Foreign Key (fkQuiz) REFERENCES Quizzes(idQuiz),
    PRIMARY KEY(idPergunta, fkQuiz)
);

CREATE TABLE alternativas(
    idAlternativa INT AUTO_INCREMENT,
    fkPergunta INT,
    resposta VARCHAR(80),
    correta TINYINT,
    Foreign Key (fkPergunta) REFERENCES Perguntas(idPergunta),
    PRIMARY KEY(idAlternativa, fkPergunta)
);

INSERT INTO quizzes VALUES 
    (DEFAULT, 'Premier League'),
    (DEFAULT, 'La Liga'),
    (DEFAULT, 'Bundesliga'),
    (DEFAULT, 'Serie A Tim'),
    (DEFAULT, 'Brasileirão'),
    (DEFAULT, 'Champions League'),
    (DEFAULT, 'Copa do Mundo'),
    (DEFAULT, 'Futebol');


    


-- Inserts de perguntas quiz premier league
INSERT INTO perguntas (fkQuiz, descricao) VALUES
(1, 'Qual clube é conhecido como "The Gunners"?'),
(1, 'Qual clube venceu a Premier League na temporada 2022/23?'),
(1, 'Qual jogador é o maior artilheiro da história da Premier League?'),
(1, 'Qual clube tem o maior número de títulos da Premier League desde 1992?'),
(1, 'Quem foi o treinador do Arsenal na temporada dos "Invincibles" (2003/04)?'),
(1, 'Qual clube é conhecido como "The Red Devils"?'),
(1, 'Qual o goleiro que tem mais clean sheets na história da Premier League?'),
(1, 'Qual clube manda seus jogos no estádio Stamford Bridge?'),
(1, 'Quem foi o goleiro do Manchester United durante a maior parte dos anos 2000?'),
(1, 'Quem foi o primeiro campeão da Premier League (1992/93)?'),
(1, 'Qual atacante egípcio é destaque do Liverpool desde 2017?'),
(1, 'Quem é o treinador do Manchester City desde 2016?'),
(1, 'Em que cidade fica o clube Aston Villa?'),
(1, 'Qual clube é conhecido como "The Toffees"?'),
(1, 'Quantos pontos somou o Manchester City ao vencer a Premier League 2017/18?'),
(1, 'Qual clube inglês tem o apelido "The Foxes"?'),
(1, 'Em que estádio o Manchester City manda seus jogos?'),
(1, 'Qual o jogo com mais gols da história da Premier League?'),
(1, 'Qual clube venceu a Premier League de forma invicta?'),
(1, 'Qual clube tem rivalidade histórica com o Everton?'),
(1, 'Qual jogador marcou o famoso "Gol Fantasma" de 2005 contra o Chelsea?'),
(1, 'Quem marcou o gol decisivo do título do Manchester City em 2011/12?'),
(1, 'Qual é o estádio do West Ham United?'),
(1, 'Quem é o maior artilheiro da história do Arsenal?'),
(1, 'Qual o jogador com mais jogos na Premier League?'),
(1, 'Em que ano o campeonato inglês passou a se chamar Premier League?'),
(1, 'Qual jogador português brilhou no Manchester United e voltou ao clube em 2021?'),
(1, 'Em que ano o Leicester City venceu a Premier League?'),
(1, 'Qual time tem o maior estádio da Premier League?'),
(1, 'Quem é o maior rival do Manchester City?'),
(1, 'Qual clube foi fundado em 1886 com o nome Dial Square?'),
(1, 'Qual o jogador com mais jogos na história do Liverpool?'),
(1, 'Quem foi técnico do Manchester United por mais de 25 anos?'),
(1, 'Qual clube foi mais vezes rebaixado na história da Premier League?'),
(1, 'Quem jogador mais venceu a chuteira de ouro na história da Premier League?'),
(1, 'Qual zagueiro holandês é um dos pilares do Liverpool desde 2018?'),
(1, 'Quantos títulos da Premier League tem o Chelsea até 2025?'),
(1, 'Qual clube tem como mascote um galo?'),
(1, 'Qual clube tem como arquirrival o Leeds United?'),
(1, 'Quem é conhecido como “Mr. Premier League”?'),
(1, 'Qual clube tinha Alan Shearer como ídolo?'),
(1, 'Qual jogador marcou um hat-trick mais rápido na história da Premier League?'),
(1, 'Quem é o treinador do Arsenal em 2023/24?'),
(1, 'Qual clube usava o estádio White Hart Lane até 2017?'),
(1, 'Qual jogador marcou mais assistências em uma única temporada da Premier League?');


-- Insert de respostas quiz premier league
INSERT INTO alternativas (fkPergunta, resposta, correta) VALUES
(1, 'Arsenal', 1),
(1, 'Chelsea', 0),
(1, 'Tottenham', 0),
(1, 'West Ham', 0),
(2, 'Manchester City', 1),
(2, 'Liverpool', 0),
(2, 'Arsenal', 0),
(2, 'Chelsea', 0),
(3, 'Alan Shearer', 1),
(3, 'Wayne Rooney', 0),
(3, 'Harry Kane', 0),
(3, 'Sergio Agüero', 0),
(4, 'Manchester United', 1),
(4, 'Chelsea', 0),
(4, 'Manchester City', 0),
(4, 'Arsenal', 0),
(5, 'Arsène Wenger', 1),
(5, 'Unai Emery', 0),
(5, 'Mikel Arteta', 0),
(5, 'George Graham', 0),
(6, 'Manchester United', 1),
(6, 'Liverpool', 0),
(6, 'Arsenal', 0),
(6, 'Manchester City', 0),
(7, 'Petr Čech', 1),
(7, 'David De Gea', 0),
(7, 'Joe Hart', 0),
(7, 'Brad Friedel', 0),
(8, 'Chelsea', 1),
(8, 'Tottenham', 0),
(8, 'Arsenal', 0),
(8, 'Fulham', 0),
(9, 'Edwin van der Sar', 1),
(9, 'Peter Schmeichel', 0),
(9, 'David De Gea', 0),
(9, 'Fabien Barthez', 0),
(10, 'Manchester United', 1),
(10, 'Blackburn Rovers', 0),
(10, 'Arsenal', 0),
(10, 'Chelsea', 0),
(11, 'Mohamed Salah', 1),
(11, 'Sadio Mané', 0),
(11, 'Roberto Firmino', 0),
(11, 'Trezeguet', 0),
(12, 'Pep Guardiola', 1),
(12, 'Manuel Pellegrini', 0),
(12, 'Roberto Mancini', 0),
(12, 'Carlo Ancelotti', 0),
(13, 'Birmingham', 1),
(13, 'Liverpool', 0),
(13, 'Manchester', 0),
(13, 'Leicester', 0),
(14, 'Everton', 1),
(14, 'West Ham', 0),
(14, 'Newcastle', 0),
(14, 'Leeds United', 0),
(15, '100', 1),
(15, '98', 0),
(15, '95', 0),
(15, '99', 0),
(16, 'Leicester City', 1),
(16, 'Brighton', 0),
(16, 'Brentford', 0),
(16, 'Crystal Palace', 0),
(17, 'Etihad Stadium', 1),
(17, 'Old Trafford', 0),
(17, 'Anfield', 0),
(17, 'Stamford Bridge', 0),
(18, 'Portsmouth 7x4 Reading', 1),
(18, 'Tottenham 6x4 Reading', 0),
(18, 'Arsenal 7x3 Newcastle', 0),
(18, 'Norwich 4x5 Liverpool', 0),
(19, 'Arsenal', 1),
(19, 'Chelsea', 0),
(19, 'Liverpool', 0),
(19, 'Manchester United', 0),
(20, 'Liverpool', 1),
(20, 'Manchester City', 0),
(20, 'Tottenham', 0),
(20, 'Arsenal', 0),
(21, 'Luis Garcia', 1),
(21, 'Steven Gerrard', 0),
(21, 'John Arne Riise', 0),
(21, 'Fernando Torres', 0),
(22, 'Sergio Agüero', 1),
(22, 'Edin Džeko', 0),
(22, 'Yaya Touré', 0),
(22, 'David Silva', 0),
(23, 'London Stadium', 1),
(23, 'Upton Park', 0),
(23, 'Craven Cottage', 0),
(23, 'Selhurst Park', 0),
(24, 'Thierry Henry', 1),
(24, 'Ian Wright', 0),
(24, 'Robin van Persie', 0),
(24, 'Dennis Bergkamp', 0),
(25, 'Gareth Barry', 1),
(25, 'Ryan Giggs', 0),
(25, 'James Milner', 0),
(25, 'Frank Lampard', 0),
(26, '1992', 1),
(26, '1990', 0),
(26, '1994', 0),
(26, '1996', 0),
(27, 'Cristiano Ronaldo', 1),
(27, 'Bruno Fernandes', 0),
(27, 'João Moutinho', 0),
(27, 'Diogo Dalot', 0),
(28, '2016', 1),
(28, '2015', 0),
(28, '2017', 0),
(28, '2014', 0),
(29, 'Manchester United', 1),
(29, 'Arsenal', 0),
(29, 'West Ham', 0),
(29, 'Liverpool', 0),
(30, 'Manchester United', 1),
(30, 'Liverpool', 0),
(30, 'Chelsea', 0),
(30, 'Tottenham', 0),
(31, 'Arsenal', 1),
(31, 'Chelsea', 0),
(31, 'Everton', 0),
(31, 'Fulham', 0),
(32, 'Jamie Carragher', 1),
(32, 'Steven Gerrard', 0),
(32, 'Ian Rush', 0),
(32, 'Mohamed Salah', 0),
(33, 'Alex Ferguson', 1),
(33, 'David Moyes', 0),
(33, 'Ron Atkinson', 0),
(33, 'Ole Gunnar Solskjær', 0),
(34, 'Norwich City', 1),
(34, 'Sunderland', 0),
(34, 'West Bromwich', 0),
(34, 'Fulham', 0),
(35, 'Thierry Henry', 1),
(35, 'Harry Kane', 0),
(35, 'Alan Shearer', 0),
(35, 'Robin van Persie', 0),
(36, 'Virgil van Dijk', 1),
(36, 'Matthijs de Ligt', 0),
(36, 'Nathan Aké', 0),
(36, 'Daley Blind', 0),
(37, '6', 1),
(37, '5', 0),
(37, '4', 0),
(37, '7', 0),
(38, 'Tottenham', 1),
(38, 'Arsenal', 0),
(38, 'Brighton', 0),
(38, 'Newcastle', 0),
(39, 'Manchester United', 1),
(39, 'Manchester City', 0),
(39, 'Everton', 0),
(39, 'Sheffield United', 0),
(40, 'James Milner', 1),
(40, 'Ryan Giggs', 0),
(40, 'Gareth Barry', 0),
(40, 'Frank Lampard', 0),
(41, 'Newcastle', 1),
(41, 'Blackburn', 0),
(41, 'Everton', 0),
(41, 'Leeds United', 0),
(42, 'Sadio Mané', 1),
(42, 'Mohamed Salah', 0),
(42, 'Cristiano Ronaldo', 0),
(42, 'Robbie Fowler', 0),
(43, 'Mikel Arteta', 1),
(43, 'Unai Emery', 0),
(43, 'Arsène Wenger', 0),
(43, 'Patrick Vieira', 0),
(44, 'Tottenham', 1),
(44, 'Arsenal', 0),
(44, 'Chelsea', 0),
(44, 'Crystal Palace', 0),
(45, 'Kevin De Bruyne', 1),
(45, 'Thierry Henry', 0),
(45, 'Cesc Fàbregas', 0),
(45, 'Ryan Giggs', 0);

INSERT INTO perguntas (fkQuiz, descricao) VALUES
--                          Perguntas fáceis
    (6, 'Qual único time a vencer a Champions League 3 vezes consecutivas?'),
    (6, 'Quem é o maior artilheiro da história da Champions League?'),
    (6, 'Qual clube tem mais títulos da Champions League?'),
    (6, ''),
    (6, ''),
    (6, ''),
    (6, 'Qual foi o primeiro clube inglês a vencer a Champions League?'),
    (6, 'Qual técnico tem mais títulos da Champions League?'),
    (6, 'Q?'),
    (6, ''),
    (6, ''),
    (6, 'Quem defendeu dois pênaltis na final de 2005?'),
    (6, 'Qual clube alemão venceu a Champions em 2013?'),
    (6, 'Qual jogador brasileiro tem mais gols na Champions League?'),
    (6, 'Qual clube eliminou o PSG nas oitavas da Champions 2022/23?'),


--                          Perguntas médias
    (6, 'Quem marcou o gol da vitória na final da Champions League de 2014?'),
    (6, 'Em que ano foi disputada a primeira edição da Champions League?'),
    (6, 'Qual clube chegou a três finais seguidas entre 2016 e 2018?'),
    (6, 'Qual país sediou a final da Champions League de 2021?'),
    (6, 'Quem marcou de bicicleta contra a Juventus na final de 2018?'),
    (6, 'Qual clube francês venceu a Champions League?'),
    (6, 'Qual jogador tem mais assistências na história da Champions League?'),
    (6, 'Quem foi o capitão do Barcelona na final de 2015?'),
    (6, 'Qual foi o adversário do Bayern na final de 2020?'),
    (6, 'Qual clube italiano venceu a Champions em 2010?'),
    (6, 'Quem é o artilheiro da Champions League 2022/23?'),
    (6, 'Qual jogador marcou um hat-trick em 11 minutos em 2019?'),
    (6, 'Qual clube inglês venceu a Champions em 1999?'),
    (6, 'Quem marcou o gol decisivo na final de 2019?'),
    (6, 'Qual treinador venceu a Champions por dois clubes diferentes?'),

--                          Perguntas difíceis
    (6, 'Qual jogador marcou um hat-trick mais rápido na história da competição?'),
    (6, 'Quem marcou na final de 2009 pelo Barcelona contra o Manchester United?'),
    (6, 'Qual zagueiro do Real Madrid é conhecido por gols em finais?'),
    (6, 'Qual clube português venceu a Champions em 2004?'),
    (6, 'Quem era o técnico do Liverpool em 2005?'),
    (6, 'Qual clube venceu a Champions de forma invicta em 2020?'),
    (6, 'Quem perdeu um pênalti decisivo na final de 2008?'),
    (6, 'Qual jogador do Ajax foi destaque em 2018/19?'),
    (6, 'Qual país tem mais clubes campeões da Champions League?'),
    (6, 'Qual jogador marcou 17 gols em uma única edição da Champions?'),
    (6, 'Quem foi o técnico do Chelsea no título de 2012?'),
    (6, 'Qual clube espanhol perdeu três finais seguidas nos anos 60?'),
    (6, 'Quem é o único jogador a marcar em três finais diferentes de Champions?'),
    (6, 'Qual foi o placar da final de 2013 entre Bayern e Dortmund?'),
    (6, 'Quem é o goleiro com mais jogos na história da Champions?'),