USE futBrain;
SHOW TABLES;

CREATE TABLE usuario(
    idUsuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(45),
    email VARCHAR(45),
    senha VARCHAR(45)  
);

CREATE TABLE quizzes(
    idQuiz INT PRIMARY KEY AUTO_INCREMENT,
    liga VARCHAR(45) UNIQUE
);

CREATE TABLE resultado(
    fkUsuario INT,
    fkQuiz INT,
    pontos INT,
    dtQuiz DATETIME,
    PRIMARY KEY (fkUsuario, fkQuiz),
    Foreign Key (fkUsuario) REFERENCES Usuario(idUsuario),
    Foreign Key (fkQuiz) REFERENCES Quizzes(idQuiz)
);

CREATE TABLE perguntas(
    idPergunta INT AUTO_INCREMENT,
    fkQuiz INT,
    descricao VARCHAR(200),
    Foreign Key (fkQuiz) REFERENCES Quizzes(idQuiz),
    PRIMARY KEY(idPergunta, fkQuiz)
);



CREATE TABLE alternativas(
    idAlternativa INT AUTO_INCREMENT,
    fkPergunta INT,
    resposta VARCHAR(80),
    correta TINYINT,
    Foreign Key (fkPergunta) REFERENCES Perguntas(idPergunta),
    PRIMARY KEY(idAlternativa, fkPergunta)
);

INSERT INTO quizzes VALUES 

    (DEFAULT, 'Premier League'),
    (DEFAULT, 'La Liga'),
    (DEFAULT, 'Bundesliga'),
    (DEFAULT, 'Serie A Tim'),
    (DEFAULT, 'Brasileirão'),
    (DEFAULT, 'Champions League'),
    (DEFAULT, 'Copa do Mundo'),
    (DEFAULT, 'Futebol');


    


-- Inserts de perguntas quiz premier league
INSERT INTO perguntas (fkQuiz, descricao) VALUES
(1, 'Qual clube é conhecido como "The Gunners"?'),
(1, 'Qual clube venceu a Premier League na temporada 2022/23?'),
(1, 'Qual jogador é o maior artilheiro da história da Premier League?'),
(1, 'Qual clube tem o maior número de títulos da Premier League desde 1992?'),
(1, 'Quem foi o treinador do Arsenal na temporada dos "Invincibles" (2003/04)?'),
(1, 'Qual clube é conhecido como "The Red Devils"?'),
(1, 'Qual o goleiro que tem mais clean sheets na história da Premier League?'),
(1, 'Qual clube manda seus jogos no estádio Stamford Bridge?'),
(1, 'Quem foi o goleiro do Manchester United durante a maior parte dos anos 2000?'),
(1, 'Quem foi o primeiro campeão da Premier League (1992/93)?'),
(1, 'Qual atacante egípcio é destaque do Liverpool desde 2017?'),
(1, 'Quem é o treinador do Manchester City desde 2016?'),
(1, 'Em que cidade fica o clube Aston Villa?'),
(1, 'Qual clube é conhecido como "The Toffees"?'),
(1, 'Quantos pontos somou o Manchester City ao vencer a Premier League 2017/18?'),
(1, 'Qual clube inglês tem o apelido "The Foxes"?'),
(1, 'Em que estádio o Manchester City manda seus jogos?'),
(1, 'Qual o jogo com mais gols da história da Premier League?'),
(1, 'Qual clube venceu a Premier League de forma invicta?'),
(1, 'Qual clube tem rivalidade histórica com o Everton?'),
(1, 'Qual jogador marcou o famoso "Gol Fantasma" de 2005 contra o Chelsea?'),
(1, 'Quem marcou o gol decisivo do título do Manchester City em 2011/12?'),
(1, 'Qual é o estádio do West Ham United?'),
(1, 'Quem é o maior artilheiro da história do Arsenal?'),
(1, 'Qual o jogador com mais jogos na Premier League?'),
(1, 'Em que ano o campeonato inglês passou a se chamar Premier League?'),
(1, 'Qual jogador português brilhou no Manchester United e voltou ao clube em 2021?'),
(1, 'Em que ano o Leicester City venceu a Premier League?'),
(1, 'Qual time tem o maior estádio da Premier League?'),
(1, 'Quem é o maior rival do Manchester City?'),
(1, 'Qual clube foi fundado em 1886 com o nome Dial Square?'),
(1, 'Qual o jogador com mais jogos na história do Liverpool?'),
(1, 'Quem foi técnico do Manchester United por mais de 25 anos?'),
(1, 'Qual clube foi mais vezes rebaixado na história da Premier League?'),
(1, 'Quem jogador mais venceu a chuteira de ouro na história da Premier League?'),
(1, 'Qual zagueiro holandês é um dos pilares do Liverpool desde 2018?'),
(1, 'Quantos títulos da Premier League tem o Chelsea até 2025?'),
(1, 'Qual clube tem como mascote um galo?'),
(1, 'Qual clássico é conhecido como ""Guerra das Flores?'),
(1, 'Quem é conhecido como “Mr. Premier League”?'),
(1, 'Qual clube tinha Alan Shearer como ídolo?'),
(1, 'Qual jogador marcou um hat-trick mais rápido na história da Premier League?'),
(1, 'Quem é o treinador do Arsenal em 2023/24?'),
(1, 'Qual clube usava o estádio White Hart Lane até 2017?'),
(1, 'Qual jogador marcou mais assistências em uma única temporada da Premier League?');


-- Insert de respostas quiz premier league
INSERT INTO alternativas (fkPergunta, resposta, correta) VALUES
(1, 'Arsenal', 1),
(1, 'Chelsea', 0),
(1, 'Tottenham', 0),
(1, 'West Ham', 0),
(2, 'Manchester City', 1),
(2, 'Liverpool', 0),
(2, 'Arsenal', 0),
(2, 'Chelsea', 0),
(3, 'Alan Shearer', 1),
(3, 'Wayne Rooney', 0),
(3, 'Harry Kane', 0),
(3, 'Sergio Agüero', 0),
(4, 'Manchester United', 1),
(4, 'Chelsea', 0),
(4, 'Manchester City', 0),
(4, 'Arsenal', 0),
(5, 'Arsène Wenger', 1),
(5, 'Unai Emery', 0),
(5, 'Mikel Arteta', 0),
(5, 'George Graham', 0),
(6, 'Manchester United', 1),
(6, 'Liverpool', 0),
(6, 'Arsenal', 0),
(6, 'Manchester City', 0),
(7, 'Petr Čech', 1),
(7, 'David De Gea', 0),
(7, 'Joe Hart', 0),
(7, 'Brad Friedel', 0),
(8, 'Chelsea', 1),
(8, 'Tottenham', 0),
(8, 'Arsenal', 0),
(8, 'Fulham', 0),
(9, 'Edwin van der Sar', 1),
(9, 'Peter Schmeichel', 0),
(9, 'David De Gea', 0),
(9, 'Fabien Barthez', 0),
(10, 'Manchester United', 1),
(10, 'Blackburn Rovers', 0),
(10, 'Arsenal', 0),
(10, 'Chelsea', 0),
(11, 'Mohamed Salah', 1),
(11, 'Sadio Mané', 0),
(11, 'Roberto Firmino', 0),
(11, 'Trezeguet', 0),
(12, 'Pep Guardiola', 1),
(12, 'Manuel Pellegrini', 0),
(12, 'Roberto Mancini', 0),
(12, 'Carlo Ancelotti', 0),
(13, 'Birmingham', 1),
(13, 'Liverpool', 0),
(13, 'Manchester', 0),
(13, 'Leicester', 0),
(14, 'Everton', 1),
(14, 'West Ham', 0),
(14, 'Newcastle', 0),
(14, 'Leeds United', 0),
(15, '100', 1),
(15, '98', 0),
(15, '95', 0),
(15, '99', 0),
(16, 'Leicester City', 1),
(16, 'Brighton', 0),
(16, 'Brentford', 0),
(16, 'Crystal Palace', 0),
(17, 'Etihad Stadium', 1),
(17, 'Old Trafford', 0),
(17, 'Anfield', 0),
(17, 'Stamford Bridge', 0),
(18, 'Portsmouth 7x4 Reading', 1),
(18, 'Tottenham 6x4 Reading', 0),
(18, 'Arsenal 7x3 Newcastle', 0),
(18, 'Norwich 4x5 Liverpool', 0),
(19, 'Arsenal', 1),
(19, 'Chelsea', 0),
(19, 'Liverpool', 0),
(19, 'Manchester United', 0),
(20, 'Liverpool', 1),
(20, 'Manchester City', 0),
(20, 'Tottenham', 0),
(20, 'Arsenal', 0),
(21, 'Luis Garcia', 1),
(21, 'Steven Gerrard', 0),
(21, 'John Arne Riise', 0),
(21, 'Fernando Torres', 0),
(22, 'Sergio Agüero', 1),
(22, 'Edin Džeko', 0),
(22, 'Yaya Touré', 0),
(22, 'David Silva', 0),
(23, 'London Stadium', 1),
(23, 'Upton Park', 0),
(23, 'Craven Cottage', 0),
(23, 'Selhurst Park', 0),
(24, 'Thierry Henry', 1),
(24, 'Ian Wright', 0),
(24, 'Robin van Persie', 0),
(24, 'Dennis Bergkamp', 0),
(25, 'Gareth Barry', 1),
(25, 'Ryan Giggs', 0),
(25, 'James Milner', 0),
(25, 'Frank Lampard', 0),
(26, '1992', 1),
(26, '1990', 0),
(26, '1994', 0),
(26, '1996', 0),
(27, 'Cristiano Ronaldo', 1),
(27, 'Bruno Fernandes', 0),
(27, 'João Moutinho', 0),
(27, 'Diogo Dalot', 0),
(28, '2016', 1),
(28, '2015', 0),
(28, '2017', 0),
(28, '2014', 0),
(29, 'Manchester United', 1),
(29, 'Arsenal', 0),
(29, 'West Ham', 0),
(29, 'Liverpool', 0),
(30, 'Manchester United', 1),
(30, 'Liverpool', 0),
(30, 'Chelsea', 0),
(30, 'Tottenham', 0),
(31, 'Arsenal', 1),
(31, 'Chelsea', 0),
(31, 'Everton', 0),
(31, 'Fulham', 0),
(32, 'Jamie Carragher', 1),
(32, 'Steven Gerrard', 0),
(32, 'Ian Rush', 0),
(32, 'Mohamed Salah', 0),
(33, 'Sir Alex Ferguson', 1),
(33, 'David Moyes', 0),
(33, 'Ron Atkinson', 0),
(33, 'Ole Gunnar Solskjær', 0),
(34, 'Norwich City', 1),
(34, 'Sunderland', 0),
(34, 'West Bromwich', 0),
(34, 'Fulham', 0),
(35, 'Thierry Henry', 1),
(35, 'Harry Kane', 0),
(35, 'Alan Shearer', 0),
(35, 'Robin van Persie', 0),
(36, 'Virgil van Dijk', 1),
(36, 'Matthijs de Ligt', 0),
(36, 'Nathan Aké', 0),
(36, 'Daley Blind', 0),
(37, '6', 1),
(37, '5', 0),
(37, '4', 0),
(37, '7', 0),
(38, 'Tottenham', 1),
(38, 'Arsenal', 0),
(38, 'Brighton', 0),
(38, 'Newcastle', 0),
(39, 'Manchester United', 1),
(39, 'Manchester City', 0),
(39, 'Everton', 0),
(39, 'Sheffield United', 0),
(40, 'James Milner', 1),
(40, 'Ryan Giggs', 0),
(40, 'Gareth Barry', 0),
(40, 'Frank Lampard', 0),
(41, 'Newcastle', 1),
(41, 'Blackburn', 0),
(41, 'Everton', 0),
(41, 'Leeds United', 0),
(42, 'Sadio Mané', 1),
(42, 'Mohamed Salah', 0),
(42, 'Cristiano Ronaldo', 0),
(42, 'Robbie Fowler', 0),
(43, 'Mikel Arteta', 1),
(43, 'Unai Emery', 0),
(43, 'Arsène Wenger', 0),
(43, 'Patrick Vieira', 0),
(44, 'Tottenham', 1),
(44, 'Arsenal', 0),
(44, 'Chelsea', 0),
(44, 'Crystal Palace', 0),
(45, 'Kevin De Bruyne', 1),
(45, 'Thierry Henry', 0),
(45, 'Cesc Fàbregas', 0),
(45, 'Ryan Giggs', 0);

select descricao, idPergunta FROM perguntas join quizzes on fkQuiz = idQuiz WHERE idQuiz = 6; 

INSERT INTO perguntas (fkQuiz, descricao) VALUES

    (6, 'Qual único time a vencer a Champions League 3 vezes consecutivas?'),
    (6, 'Quem é o maior artilheiro da história da Champions League?'),
    (6, 'Qual clube tem mais títulos da Champions League?'),
    (6, 'Qual foi o primeiro clube inglês a vencer a Champions League?'),
    (6, 'Qual técnico tem mais títulos da Champions League?'),
    (6, 'Qual jogador brasileiro tem mais gols na Champions League?'),
    (6, 'Qual jogador tem mais assistências na história da Champions League?'),
    (6, 'Qual o recorde de gols de uma única edição da Champions?'),
    (6, 'Quem fez o recorde de gols em uma única edição da Champions?'),
    (6, 'Quem é o primeiro jogador a marcar em três finais diferentes de Champions?'),
    (6, 'Qual país tem mais clubes campeões da Champions League?'),
    (6, 'Em que ano a Champions League passou a ter esse nome (antes era chamada de Copa dos Campeões da Europa)?'),
    (6, 'Quem marcou dois gols na final de 2018 entre Real Madrid e Liverpool?'),
    (6, 'Qual foi o primeiro clube alemão a vencer a Champions League?'),
    (6, 'Qual jogador marcou de voleio na final de 2002 entre Real Madrid e Bayer Leverkusen?'),
    (6, 'Quais os países que mais sediaram finais de Champions?'),
    (6, 'Qual estádio mais sediou finais de Champions?'),
    (6, 'Qual destes jogadores NÃO tem 6 títulos de Champions?'),
    (6, 'Qual técnico detém o recorde de mais vitórias na fase eliminatória da Champions?'),
    



    (6, 'Quem marcou o gol da vitória na final da Champions League de 2014?'),
    (6, 'Em que ano foi disputada a primeira edição da Champions League?'),
    (6, 'Qual clube português venceu a Champions em 2004?'),
    (6, 'Quem é o goleiro com mais jogos na história da Champions?'),
    (6, 'Qual jogador marcou o gol mais rápido da história de uma final da Champions League?'),
    (6, 'Qual jogador fez mais assistências em uma única edição?'),
    (6, 'Quantos clubes diferentes venceram a Champions League entre 2000 e 2020?'),
    (6, 'Quem foi o primeiro jogador a marcar em três finais diferentes da Champions League?'),
    (6, 'Qual jogador foi campeão da Champions por três clubes diferentes?'),
    (6, 'Qual clube teve mais finais perdidas na Champions League até 2025?'),
    (6, 'Quem foi o primeiro jogador africano a ser artilheiro isolado de uma edição da Champions League?'),
    (6, 'Qual técnico tem mais títulos de Champions League?'),
    (6, 'Na semi final da champions 2019 lucas moura fez 3 gols, o seu terceiro foi no minuto?'),
    (6, 'Qual o estádio da primeira final da Champions?'),
    (6, 'Qual equipe com mais vices na história da Champions?'),

    

    (6, 'Qual jogador marcou um hat-trick mais rápido na história da competição?'),
    (6, 'De qual país foi o primeiro clube não europeu a disputar uma fase preliminar da Champions League?'),
    (6, 'Qual jogador marcou mais gols em uma única edição da Copa dos Campeões (antes da Champions)?'),
    (6, 'Qual final de Champions League teve mais gols marcados (tempo regulamentar + prorrogação)?'),
    (6, 'Qual clube da Europa Oriental foi campeão da Champions League/Copa dos Campeões?'),
    (6, 'Qual destes clubes NUNCA ganhou a Champions?'),
    (6, 'Quem foram os únicos três jogadores que marcaram 5 gols em uma partida de Champions League?'),
    (6, 'Qual destes clubes o Real Madrid NUNCA venceu na Champions?'),
    (6, 'Quantos times diferentes já ganharam a Champions?'),
    (6, 'O hino da Champions é composto por três idiomas diferentes, quais são?'),
    (6, 'Qual foi a primeira final da Champions League?');



INSERT INTO alternativas (fkPergunta, resposta, correta) VALUES

    (46, 'Real Madrid', 1),
    (46, 'Milan', 0),
    (46, 'Bayern de Munique', 0),
    (46, 'Barcelona', 0),
    (47, 'Cristiano Ronaldo', 1),
    (47, 'Lewandowski', 0),
    (47, 'Messi', 0),
    (47, 'Raúl Gonzales', 0),
    (48, 'Real Madrid', 1),
    (48, 'Milan', 0),
    (48, 'Liverpool', 0),
    (48, 'Bayern de Munique', 0),
    (49, 'Manchester United', 1),
    (49, 'Liverpool', 0),
    (49, 'Nottingham Forest', 0),
    (49, 'Aston Villa', 0),
    (50, 'Carlo Ancelotti', 1),
    (50, 'Pep Guardiola', 0),
    (50, 'José Mourinho', 0),
    (50, 'Sir Alex Ferguson', 0),
    (51, 'Neymar Jr', 1),
    (51, 'Vinicius Jr', 0),
    (51, 'Ronaldo Fênomeno', 0),
    (51, 'Rodrygo', 0),
    (52, 'Cristiano Ronaldo', 1),
    (52, 'Lionel Messi', 0),
    (52, 'Kevin de Bruyne', 0),
    (52, 'Mohamed Salah', 0),
    (53, '17', 1),
    (53, '18', 0),
    (53, '15', 0),
    (53, '16', 0),
    (54, 'Cristiano Ronaldo', 1),
    (54, 'Haaland', 0),
    (54, 'Lewandowski', 0),
    (54, 'Messi', 0),
    (55, 'Alfredo Di Stéfano', 1),
    (55, 'Ferenc Puskás', 0),
    (55, 'Eusébio', 0),
    (55, 'Pelé', 0),
    (56, 'Inglaterra', 1),
    (56, 'Espanha', 0),
    (56, 'Itália', 0),
    (56, 'Alemanha', 0),
    (57, '1992-93', 1),
    (57, '1995-96', 0),
    (57, '2000-01', 0),
    (57, '1988-89', 0),
    (58, 'Gareth Bale', 1),
    (58, 'Karim Benzema', 0),
    (58, 'Sadio Mané', 0),
    (58, 'Mohamed Salah', 0),
    (59, 'Bayern de Munique', 1),
    (59, 'Borussia Dortmund', 0),
    (59, 'Hamburgo', 0),
    (59, 'Bayer Leverkusen', 0),
    (60, 'Zinedine Zidane', 1),
    (60, 'Raúl', 0),
    (60, 'Fernando Morientes', 0),
    (60, 'Michael Ballack', 0),
    (61, 'Inglaterra , Itália e Alemanha', 1),
    (61, 'França ,Itália e Alemanha', 0),
    (61, 'França e Espanha', 0),
    (61, 'Alemanha e Inglaterra', 0),
    (62, 'Wembley Stadium (Londres)', 1),
    (62, 'Santiago Bernabéu (Madrid)', 0),
    (62, 'San Siro (Milan)', 0),
    (62, 'Stade de France (Paris)', 0),
    (63, 'Cristiano Ronaldo', 1),
    (63, 'Modric', 0),
    (63, 'Carvajal', 0),
    (63, 'Francisco Gento', 0),
    (64, 'Cristiano Ronaldo', 1),
    (64, 'Messi', 0),
    (64, 'Sergio Ramos', 0),
    (64, 'Di Stéfano', 0),
    (65, 'Gareth Bale', 1),
    (65, 'Sergio Ramos', 0),
    (65, 'Ángel Di María', 0),
    (65, 'Cristiano Ronaldo', 0),
    (66, '1955-56', 1),
    (66, '1960-61', 0),
    (66, '1970-71', 0),
    (66, '1985-86', 0),
    (67, 'Porto', 1),
    (67, 'Benfica', 0),
    (67, 'Sporting', 0),
    (67, 'Boavista', 0),
    (68, 'Iker Casillas', 1),
    (68, 'Gianluigi Buffon', 0),
    (68, 'Petr Čech', 0),
    (68, 'Manuel Neuer', 0),
    (69, 'Paolo Maldini', 1),
    (69, 'Alessandro Del Piero', 0),
    (69, 'Karl-Heinz Riedle', 0),
    (69, 'Gaizka Mendieta', 0),
    (70, 'Luis Figo', 1),
    (70, 'Messi', 0),
    (70, 'Cristiano Ronaldo', 0),
    (70, 'Kevin de bruyne', 0),
    (71, '12', 1),
    (71, '10', 0),
    (71, '15', 0),
    (71, '18', 0),
    (72, 'Alfredo Di Stéfano', 1),
    (72, 'Ferenc Puskás', 0),
    (72, 'Eusébio', 0),
    (72, 'Pelé', 0),
    (73, 'Clarence Seedorf', 1),
    (73, 'Samuel Eto\'o', 0),
    (73, 'Zlatan Ibrahimović', 0),
    (73, 'Deco', 0),
    (74, 'Juventus', 1),
    (74, 'Bayern de Munique', 0),
    (74, 'Benfica', 0),
    (74, 'Milan', 0),
    (75, 'George Weah', 1),
    (75, 'Samuel Eto\'o', 0),
    (75, 'Didier Drogba', 0),
    (75, 'Mohamed Salah', 0),
    (76, 'Carlo Ancelotti', 1),
    (76, 'Pep Guardiola', 0),
    (76, 'Zinedine Zidane', 0),
    (76, 'Jürgen Klopp', 0),
    (77, '90+6', 1),
    (77, '90+3', 0),
    (77, '90+1', 0),
    (77, '90+5', 0),
    (78, 'Parc des Princes (Paris)', 1),
    (78, 'Estádio de Wembley (Londres)', 0),
    (78, 'Estádio Santiago Bernabéu (Madrid)', 0),
    (78, 'Estádio Olímpico de Roma', 0),
    (79, 'Juventus', 1),
    (79, 'Milan', 0),
    (79, 'Bayern de Munique', 0),
    (79, 'Benfica', 0),
    (80, 'Bafétimbi Gomis', 1),
    (80, 'Mike Newell', 0),
    (80, 'Marco van Basten', 0),
    (80, 'Clarence Seedorf', 0),
    (81, 'Israel', 1),
    (81, 'Gibraltar', 0),
    (81, 'Cazaquistão', 0),
    (81, 'Armênia', 0),
    (82, 'Just Fontaine', 1),
    (82, 'José Altafini "Mazzola"', 0),
    (82, 'Ferenc Puskás', 0),
    (82, 'Alfredo Di Stéfano', 0),
    (83, 'Real Madrid 7x3 Eintracht Frankfurt (1960)', 1),
    (83, 'Milan 4x0 Steaua București (1989)', 0),
    (83, 'Real Madrid 2x1 Stade de Reims (1959)', 0),
    (83, 'Benfica 5x3 Real Madrid (1962)', 0),
    (84, 'Steaua București (Romênia)', 1),
    (84, 'Estrela Vermelha (Sérvia)', 0),
    (84, 'Dynamo Kiev (Ucrânia)', 0),
    (84, 'Ferencváros (Hungria)', 0),
    (85, 'Club Brugge', 1),
    (85, 'Nottingham Forest', 0),
    (85, 'Aston Villa', 0),
    (85, 'Steaua București', 0),
    (86, 'Luiz Adriano, Lionel Messi, Erling Haaland', 1),
    (86, 'Cristiano Ronaldo, Robert Lewandowski, Zlatan Ibrahimović', 0),
    (86, 'Raúl González, Ruud van Nistelrooy, Filippo Inzaghi', 0),
    (86, 'Kylian Mbappé, Neymar, Karim Benzema', 0),
    (87, 'Arsenal', 1),
    (87, 'Barcelona', 0),
    (87, 'Manchester United', 0),
    (87, 'Juventus', 0),
    (88, '23', 1),
    (88, '19', 0),
    (88, '25', 0),
    (88, '16', 0),
    (89, 'Francês, Inglês e Alemão', 1),
    (89, 'Espanhol, Inglês e Italiano', 0),
    (89, 'Latim, Inglês e Francês', 0),
    (89, 'Italiano, Alemão e Espanhol', 0),
    (90, 'Real Madrid 4x3 Stade de Reims', 1),
    (90, 'Benfica 3x2 Barcelona', 0),
    (90, 'Milan 2x1 Benfica', 0),
    (90, 'Inter de Milão 2x1 Real Madrid', 0);
    
    select * from perguntas where idPergunta = 56;
    use futbrain;